# Generated by Django 6.0.6 on 2026-07-14 04:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_credittransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Automatic % discount on POS sales for members of this tier.', max_digits=5)),
                ('points_per_hundred', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Loyalty points earned per ৳100 spent.', max_digits=8)),
                ('min_points', models.PositiveIntegerField(default=0, help_text='Minimum lifetime points to qualify / auto-upgrade into this tier.')),
                ('credit_limit_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Extra udhar limit granted with this membership.', max_digits=12)),
                ('color', models.CharField(default='#0b6e4f', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False, help_text='Built-in tiers (Silver/Gold/Loyal/Platinum) cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('benefits', models.TextField(blank=True, help_text='Human-readable benefits list for the membership card.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membership_tiers',
                'ordering': ['sort_order', 'min_points', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='lifetime_points',
            field=models.PositiveIntegerField(default=0, help_text='Total points ever earned — used for auto tier upgrades.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoyaltyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('PERCENT_OFF', 'Percent off'), ('FIXED_OFF', 'Fixed amount off'), ('BONUS_POINTS', 'Bonus points'), ('FREEBIE', 'Free item / perk')], default='PERCENT_OFF', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percent, taka amount, or bonus points depending on offer type.', max_digits=12)),
                ('points_cost', models.PositiveIntegerField(default=0, help_text='Points required to redeem. 0 = auto / membership perk (no redeem).')),
                ('min_points_balance', models.PositiveIntegerField(default=0, help_text='Customer must hold at least this many points to see the offer.')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(blank=True, help_text='Restrict to one membership. Empty = all members.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.membershiptier')),
            ],
            options={
                'db_table': 'loyalty_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='orders.membershiptier'),
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('EARN', 'Earned from purchase'), ('REDEEM', 'Redeemed for offer'), ('BONUS', 'Bonus / promotion'), ('ADJUST', 'Manual adjustment'), ('UPGRADE', 'Membership upgrade gift')], max_length=20)),
                ('points', models.IntegerField(help_text='Signed: positive earn, negative redeem.')),
                ('balance_after', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to='orders.customer')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='orders.loyaltyoffer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='orders.salesorder')),
            ],
            options={
                'db_table': 'points_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
