# Generated by Django 6.0.6 on 2026-07-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(default='pcs', max_length=20),
        ),
    ]
